# permissions for end users to view federatedclonesets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: federatedcloneset-viewer-role
rules:
- apiGroups:
  - federation.kruise.io
  resources:
  - federatedclonesets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - federation.kruise.io
  resources:
  - federatedclonesets/status
  verbs:
  - get
